In [1]:
import torch
import numpy as np

In [2]:
x = torch.empty(5, 3)
x

tensor([[1.3563e-19, 1.8888e+31, 8.9066e-15],
        [1.8888e+31, 6.4639e-04, 6.8608e+22],
        [1.7753e+28, 2.0535e-19, 7.5563e+31],
        [1.8014e+25, 8.1335e+32, 7.2436e+22],
        [7.5554e+28, 2.9635e+29, 2.2087e+03]])

In [3]:
x.dtype

torch.float32

In [4]:
x = torch.rand(5, 3)
x

tensor([[0.3786, 0.6417, 0.0528],
        [0.5310, 0.5576, 0.7258],
        [0.0905, 0.0600, 0.2702],
        [0.4386, 0.5008, 0.8609],
        [0.8343, 0.5524, 0.3796]])

In [5]:
x = torch.tensor([5.5, 3])
x

tensor([5.5000, 3.0000])

In [6]:
x = x.new_ones(5, 3)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [7]:
x = torch.rand_like(x)
x

tensor([[0.7685, 0.3971, 0.2786],
        [0.2656, 0.8349, 0.8503],
        [0.4400, 0.7085, 0.4896],
        [0.7973, 0.3207, 0.1990],
        [0.9543, 0.7962, 0.3696]])

In [8]:
x.size()

torch.Size([5, 3])

In [9]:
x.size()[0]

5

In [10]:
y = torch.ones(5,3)
x + y

tensor([[1.7685, 1.3971, 1.2786],
        [1.2656, 1.8349, 1.8503],
        [1.4400, 1.7085, 1.4896],
        [1.7973, 1.3207, 1.1990],
        [1.9543, 1.7962, 1.3696]])

In [11]:
c = torch.empty(5, 3)
torch.add(x, y, out=c)
c

tensor([[1.7685, 1.3971, 1.2786],
        [1.2656, 1.8349, 1.8503],
        [1.4400, 1.7085, 1.4896],
        [1.7973, 1.3207, 1.1990],
        [1.9543, 1.7962, 1.3696]])

In [12]:
# is post-fixed with an _
y.add_(x)
y

tensor([[1.7685, 1.3971, 1.2786],
        [1.2656, 1.8349, 1.8503],
        [1.4400, 1.7085, 1.4896],
        [1.7973, 1.3207, 1.1990],
        [1.9543, 1.7962, 1.3696]])

In [13]:
x[:, 0]

tensor([0.7685, 0.2656, 0.4400, 0.7973, 0.9543])

In [14]:
# resize
x = torch.rand(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [15]:
# scalar
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.6748])
-0.6748170256614685


In [16]:
y = torch.tensor([6.9], dtype=torch.float32)
print(y.item())

6.900000095367432


In [17]:
# to numpy
a = torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [18]:
a.numpy()

array([1., 1., 1., 1., 1.], dtype=float32)

In [19]:
# torch Tensor is changing based on numpy array
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [20]:
x = torch.randn(1)
if torch.cuda.is_available():
    device = torch.device('cuda')
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x + y
    print(z)
    print(x.to('cpu', torch.double))

tensor([0.6172], device='cuda:0')
tensor([-0.3828], dtype=torch.float64)


In [24]:
x = torch.rand((3,3))
print(x)
print(x.dtype)
# add a dimension
# from [a, b, c] to [[a, b, c]]
x = x.unsqueeze(0)
print(x)

tensor([[0.2523, 0.7054, 0.2914],
        [0.9906, 0.2251, 0.0645],
        [0.4559, 0.3949, 0.0809]])
torch.float32
tensor([[[0.2523, 0.7054, 0.2914],
         [0.9906, 0.2251, 0.0645],
         [0.4559, 0.3949, 0.0809]]])


In [7]:
a = torch.tensor([1., 2., 3.])
b = torch.tensor([1., 3., 3.])
c = torch.eq(a, b)
a[c]

tensor([1., 3.])

In [5]:
a.dtype

torch.float32

In [6]:
a = a.int()
a.dtype

torch.int32

In [8]:
c[c==True]

tensor([True, True])