In [5]:
from __future__ import print_function
import torch

In [6]:
x = torch.empty(5, 3)
x

tensor([[2.3885e-35, 4.5675e-41, 2.3885e-35],
        [4.5675e-41, 4.4842e-44, 0.0000e+00],
        [9.1084e-44, 0.0000e+00, 1.4897e-36],
        [0.0000e+00, 1.4970e-36, 0.0000e+00],
        [8.9683e-44, 0.0000e+00, 4.6243e-44]])

In [7]:
x.dtype

torch.float32

In [9]:
x = torch.rand(5, 3)
x

tensor([[0.3659, 0.4872, 0.1490],
        [0.2794, 0.1206, 0.9869],
        [0.3831, 0.1711, 0.6401],
        [0.3828, 0.0753, 0.5993],
        [0.1493, 0.2980, 0.2442]])

In [10]:
x = torch.tensor([5.5, 3])
x

tensor([5.5000, 3.0000])

In [11]:
x = x.new_ones(5, 3)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [13]:
x = torch.rand_like(x)
x

tensor([[1.2346e-01, 5.2306e-01, 1.5118e-01],
        [5.6971e-01, 6.0274e-01, 2.6908e-01],
        [2.7029e-02, 8.6361e-01, 6.1141e-02],
        [6.8797e-01, 5.5363e-01, 1.6456e-01],
        [3.1764e-01, 1.3759e-01, 4.4167e-05]])

In [14]:
x.size()

torch.Size([5, 3])

In [17]:
x.size()[0]

5

In [18]:
y = torch.ones(5,3)
x + y

tensor([[1.1235, 1.5231, 1.1512],
        [1.5697, 1.6027, 1.2691],
        [1.0270, 1.8636, 1.0611],
        [1.6880, 1.5536, 1.1646],
        [1.3176, 1.1376, 1.0000]])

In [20]:
c = torch.empty(5, 3)
torch.add(x, y, out=c)
c

tensor([[1.1235, 1.5231, 1.1512],
        [1.5697, 1.6027, 1.2691],
        [1.0270, 1.8636, 1.0611],
        [1.6880, 1.5536, 1.1646],
        [1.3176, 1.1376, 1.0000]])

In [23]:
# is post-fixed with an _
y.add_(x)
y

tensor([[1.2469, 2.0461, 1.3024],
        [2.1394, 2.2055, 1.5382],
        [1.0541, 2.7272, 1.1223],
        [2.3759, 2.1073, 1.3291],
        [1.6353, 1.2752, 1.0001]])

In [25]:
x[:, 0]

tensor([0.1235, 0.5697, 0.0270, 0.6880, 0.3176])

In [27]:
# resize
x = torch.rand(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [28]:
# scalar
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.6803])
-0.6803086400032043


In [33]:
y = torch.tensor([6.9], dtype=torch.float32)
print(y.item())

6.900000095367432


In [34]:
# to numpy
a = torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [35]:
a.numpy()

array([1., 1., 1., 1., 1.], dtype=float32)

In [37]:
# torch Tensor is changing based on numpy array
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [39]:
x = torch.randn(1)
if torch.cuda.is_available():
    device = torch.device('cuda')
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x + y
    print(z)
    print(x.to('cpu', torch.double))

tensor([1.9910], device='cuda:0')
tensor([0.9910], dtype=torch.float64)
