In [1]:
import torch
import torch.nn.functional as F
import numpy as np

In [2]:
x = torch.randn(5)
print(x)
x_in = (x - x.min()) / (x.max()-x.min()) - .5
print(x_in)

tensor([-0.7564,  0.6910,  0.2585, -0.1423,  0.5793])
tensor([-0.5000,  0.5000,  0.2012, -0.0757,  0.4229])


In [3]:
bound = [-.5, 5]
bmul = (bound[1] - bound[0])/2.
bplus = sum(bound)/2.
print(bmul, bplus)

2.75 2.25


In [4]:
x_tanh = torch.tanh(x)
print(x_tanh)

tensor([-0.6390,  0.5986,  0.2529, -0.1414,  0.5222])


In [5]:
torch.tanh(x)*bmul+bplus

tensor([0.4928, 3.8961, 2.9454, 1.8612, 3.6859])

In [6]:
F.hardtanh(x)*bmul+bplus

tensor([0.1698, 4.1501, 2.9608, 1.8586, 3.8431])

In [7]:
torch.tanh(x_in)*bmul+bplus

tensor([0.9792, 3.5208, 2.7960, 2.0422, 3.3482])

In [8]:
F.hardtanh(x_in)*bmul+bplus

tensor([0.8750, 3.6250, 2.8033, 2.0418, 3.4129])

In [9]:
def artanh(x, eps=1e-6):
    assert isinstance(x, torch.Tensor)
    x = x * (1-eps)  # enhance numeric stability. avoid divide zero
    return .5 * torch.log((x+1.) / (1.-x))

In [10]:
artanh(x_tanh)

tensor([-0.7564,  0.6910,  0.2585, -0.1423,  0.5793])